#!/bin/bash

mc_versions="1.3.2 1.4.7 1.5.2 1.6.4 1.7.10 1.8.9 1.9.4 1.10.2 1.11.2 1.12.2 1.13.2"
echo "Available MC versions: ${mc_versions}"

while [ true ]; do
    echo -n "Enter the version you want to use: "
    read version

    valid="F"
    for i in ${mc_versions}; do
        if [ "${i}" == "${version}" ]; then
            valid="T"
        fi
    done

    if [ "${valid}" == "F" ]; then
        echo "Invalid MC version!"
    else
        break
    fi
done

export MC_VERSION="${version}"
echo "Starting Gradle with MC version ${MC_VERSION}..."
./gradlew yarn
